server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sandbox
    username: "adaumir"
    password: "021093"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
